import { useState } from 'react';
import jsPDF from 'jspdf';

/**
 * Generates a clean markdown summary from an AI message for copying/sharing.
 */
function generateMarkdown(message) {
  const llm = message.metadata?.llmResponse;
  const pubs = message.metadata?.publications || [];
  const trials = message.metadata?.clinicalTrials || [];

  let md = '# Curalink Research Report\n\n';

  if (llm?.conditionOverview) {
    md += `## Condition Overview\n${llm.conditionOverview}\n\n`;
  }

  if (llm?.researchInsights?.length) {
    md += '## Research Insights\n';
    llm.researchInsights.forEach((ins, i) => {
      md += `${i + 1}. **${ins.insight}** ${ins.citation || ''}\n`;
      if (ins.detail) md += `   ${ins.detail}\n`;
    });
    md += '\n';
  }

  if (pubs.length) {
    md += `## Source Publications (${pubs.length})\n`;
    pubs.forEach((p, i) => {
      md += `${i + 1}. [${p.title}](${p.url}) — ${p.source}, ${p.year}\n`;
    });
    md += '\n';
  }

  if (trials.length) {
    md += `## Clinical Trials (${trials.length})\n`;
    trials.forEach((t, i) => {
      md += `${i + 1}. **${t.title}** — ${t.status}\n`;
      if (t.url) md += `   [View Trial](${t.url})\n`;
    });
    md += '\n';
  }

  if (llm?.drugSafetyNote) {
    md += `## ⚠️ Drug Safety Note\n${llm.drugSafetyNote}\n\n`;
  }

  if (llm?.personalizedNote) {
    md += `## Personalized Note\n${llm.personalizedNote}\n\n`;
  }

  if (llm?.keyTakeaways?.length) {
    md += '## Key Takeaways\n';
    llm.keyTakeaways.forEach((t) => {
      md += `- ${t}\n`;
    });
    md += '\n';
  }

  if (llm?.citations?.length) {
    md += '## Citations\n';
    llm.citations.forEach((c) => {
      md += `- ${c.id}: ${c.apa || c.vancouver || ''}\n`;
    });
    md += '\n';
  }

  md += '_Generated by Curalink — AI Medical Research Assistant_\n';
  return md;
}

/**
 * Generate a branded PDF report from an AI message.
 */
function generatePDFReport(message) {
  const llm = message.metadata?.llmResponse;
  const pubs = message.metadata?.publications || [];
  const trials = message.metadata?.clinicalTrials || [];
  const doc = new jsPDF();

  let y = 20;
  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth() - margin * 2;

  const addText = (text, size = 10, style = 'normal', color = [50, 50, 50]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageWidth);
    lines.forEach((line) => {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += size * 0.5 + 2;
    });
    y += 2;
  };

  // Header
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, 220, 35, 'F');
  doc.setTextColor(45, 212, 191);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Curalink', margin, 18);
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(10);
  doc.text('AI Medical Research Report', margin, 28);
  doc.setTextColor(130, 130, 130);
  doc.setFontSize(8);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 150, 28);

  y = 45;

  // Condition Overview
  if (llm?.conditionOverview) {
    addText('CONDITION OVERVIEW', 13, 'bold', [45, 212, 191]);
    addText(llm.conditionOverview, 10, 'normal', [80, 80, 80]);
    y += 5;
  }

  // Research Insights
  if (llm?.researchInsights?.length) {
    addText('RESEARCH INSIGHTS', 13, 'bold', [129, 140, 248]);
    llm.researchInsights.forEach((ins, i) => {
      addText(`${i + 1}. ${ins.insight} ${ins.citation || ''}`, 10, 'bold', [60, 60, 60]);
      if (ins.detail) addText(`   ${ins.detail}`, 9, 'normal', [100, 100, 100]);
    });
    y += 5;
  }

  // Drug Safety
  if (llm?.drugSafetyNote) {
    addText('⚠ DRUG SAFETY NOTE', 13, 'bold', [255, 107, 107]);
    addText(llm.drugSafetyNote, 10, 'normal', [80, 80, 80]);
    y += 5;
  }

  // Publications
  if (pubs.length) {
    addText(`SOURCE PUBLICATIONS (${pubs.length})`, 13, 'bold', [56, 189, 248]);
    pubs.forEach((p, i) => {
      addText(`${i + 1}. ${p.title} — ${p.source}, ${p.year}`, 9, 'normal', [80, 80, 80]);
    });
    y += 5;
  }

  // Clinical Trials
  if (trials.length) {
    addText(`CLINICAL TRIALS (${trials.length})`, 13, 'bold', [244, 114, 182]);
    trials.forEach((t, i) => {
      addText(`${i + 1}. ${t.title} — ${t.status}`, 9, 'normal', [80, 80, 80]);
    });
    y += 5;
  }

  // Key Takeaways
  if (llm?.keyTakeaways?.length) {
    addText('KEY TAKEAWAYS', 13, 'bold', [45, 212, 191]);
    llm.keyTakeaways.forEach((t) => {
      addText(`• ${t}`, 10, 'normal', [80, 80, 80]);
    });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Curalink — AI Medical Research Assistant. This is not medical advice.', margin, 288);

  doc.save('curalink-research-report.pdf');
}

export function CopyButton({ message }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      const md = generateMarkdown(message);
      await navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  return (
    <button
      className="action-btn"
      onClick={handleCopy}
      title="Copy research to clipboard"
    >
      {copied ? (
        <>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
            <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
          </svg>
          Copy
        </>
      )}
    </button>
  );
}

export function ExportButton({ message }) {
  const handleExport = () => {
    if (message) {
      generatePDFReport(message);
    } else {
      window.print();
    }
  };

  return (
    <button className="action-btn" onClick={handleExport} title="Download PDF report">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export PDF
    </button>
  );
}

export function ShareButton({ message }) {
  const [shared, setShared] = useState(false);

  const handleShare = async () => {
    const md = generateMarkdown(message);
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Curalink Research', text: md });
      } catch {
        // User cancelled
      }
    } else {
      try {
        await navigator.clipboard.writeText(md);
        setShared(true);
        setTimeout(() => setShared(false), 2000);
      } catch (err) {
        console.error('Share failed:', err);
      }
    }
  };

  return (
    <button className="action-btn" onClick={handleShare} title="Share research">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
        <circle cx="18" cy="5" r="3" />
        <circle cx="6" cy="12" r="3" />
        <circle cx="18" cy="19" r="3" />
        <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
        <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
      </svg>
      {shared ? 'Copied!' : 'Share'}
    </button>
  );
}
