import { useState } from 'react';

/**
 * Generates a clean markdown summary from an AI message for copying/sharing.
 */
function generateMarkdown(message) {
  const llm = message.metadata?.llmResponse;
  const pubs = message.metadata?.publications || [];
  const trials = message.metadata?.clinicalTrials || [];

  let md = '# Curalink Research Report\n\n';

  if (llm?.conditionOverview) {
    md += `## Condition Overview\n${llm.conditionOverview}\n\n`;
  }

  if (llm?.researchInsights?.length) {
    md += '## Research Insights\n';
    llm.researchInsights.forEach((ins, i) => {
      md += `${i + 1}. **${ins.insight}** ${ins.citation || ''}\n`;
      if (ins.detail) md += `   ${ins.detail}\n`;
    });
    md += '\n';
  }

  if (pubs.length) {
    md += `## Source Publications (${pubs.length})\n`;
    pubs.forEach((p, i) => {
      md += `${i + 1}. [${p.title}](${p.url}) — ${p.source}, ${p.year}\n`;
    });
    md += '\n';
  }

  if (trials.length) {
    md += `## Clinical Trials (${trials.length})\n`;
    trials.forEach((t, i) => {
      md += `${i + 1}. **${t.title}** — ${t.status}\n`;
      if (t.url) md += `   [View Trial](${t.url})\n`;
    });
    md += '\n';
  }

  if (llm?.personalizedNote) {
    md += `## Personalized Note\n${llm.personalizedNote}\n\n`;
  }

  if (llm?.keyTakeaways?.length) {
    md += '## Key Takeaways\n';
    llm.keyTakeaways.forEach((t) => {
      md += `- ${t}\n`;
    });
    md += '\n';
  }

  md += '_Generated by Curalink — AI Medical Research Assistant_\n';
  return md;
}

export function CopyButton({ message }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      const md = generateMarkdown(message);
      await navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  return (
    <button
      className="action-btn"
      onClick={handleCopy}
      title="Copy research to clipboard"
    >
      {copied ? (
        <>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
            <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
          </svg>
          Copy
        </>
      )}
    </button>
  );
}

export function ExportButton() {
  const handleExport = () => {
    window.print();
  };

  return (
    <button className="action-btn" onClick={handleExport} title="Export as PDF">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export PDF
    </button>
  );
}

export function ShareButton({ message }) {
  const [shared, setShared] = useState(false);

  const handleShare = async () => {
    const md = generateMarkdown(message);
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Curalink Research', text: md });
      } catch {
        // User cancelled
      }
    } else {
      try {
        await navigator.clipboard.writeText(md);
        setShared(true);
        setTimeout(() => setShared(false), 2000);
      } catch (err) {
        console.error('Share failed:', err);
      }
    }
  };

  return (
    <button className="action-btn" onClick={handleShare} title="Share research">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: 13, height: 13 }}>
        <circle cx="18" cy="5" r="3" />
        <circle cx="6" cy="12" r="3" />
        <circle cx="18" cy="19" r="3" />
        <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
        <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
      </svg>
      {shared ? 'Copied!' : 'Share'}
    </button>
  );
}
